language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
    - pypy3
install:
    - pip install zc.buildout
    - buildout bootstrap
    - buildout
script:
    - bin/test -v1
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
