# Currently the builds use @dataflake's Appveyor account.  The PyPI token belongs
# to zope.wheelbuilder, which is managed by @mgedmin and @dataflake.

environment:
  global:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD:
      secure: vSlDBj79vziJOA5k3z16r0q5r//oezNWPJuIyZKwz2GpTwY115Rq2xW/gcj9CsUVpdUYS2OPYiwlAzjTbTTjlb2Ik57qpR4Mp+Dq5ePB8Aa7cn0X6L40egBJ4QEJvm9ugg/sdOGaHVLowMhQQvEzJlsbLm6hZu26cbU2kXTVH9f3JnOFjsTWkVuRkjLvg0a0TWMXPeXekLde9s/LIFUEvG+Flcs/ifTHD8QiWVCvr1Ctqg6QBoywDC2oBe+MUtV3p519rRWShPkEzFFlYbCHPw==

  matrix:
    - python: 27
    - python: 27-x64
    - python: 35
    - python: 35-x64
    - python: 36
    - python: 36-x64
    - python: 37
    - python: 37-x64
    - python: 38
    - python: 38-x64

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - pip install -e .

build_script:
  - pip install -U setuptools
  - pip install wheel
  - python -W ignore setup.py -q bdist_wheel

test_script:
  - python setup.py test -q

artifacts:
  - path: 'dist\*.whl'
    name: wheel

deploy_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { pip install twine; twine upload dist\*.whl }

deploy: on
